# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m

# AndroidX package structure
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=36

# Multi-drive Windows Kotlin incremental compilation fix
kotlin.incremental=false
kotlin.incremental.java=false
kotlin.incremental.js=false
